### ISSUE TITLE
Request a matching dark theme

### ISSUE THREAD

**Issue by JerryZhangZZY** [EvanNotFound/typora-theme-redefine#1]
Very nice design! Hope for a dark theme.

**Comment by EvanNotFound** [comment]
In development

**Comment by EvanNotFound** [comment]
Development completed. Please go check https://github.com/EvanNotFound/typora-theme-redefine/releases/tag/v1.0.0 and update the theme

**Comment by JerryZhangZZY** [comment]
Well done, mate
